import ConvexClientProvider from "@/components/ConvexClientProvider";
import QueryClientProvider from "@/components/QueryClientProvider";
import { Toaster } from "@/components/ui/sonner";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/convex.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider
          dynamic
          localization={{
            signIn: {
              start: {
                titleCombined: "Login to your account",
                subtitleCombined:
                  "Enter your email below to login to your account",
              },
            },
            dividerText: "Or continue with",
            socialButtonsBlockButton: `Login with {{provider|titleize}}`,
          }}
        >
          <ConvexClientProvider>
            <QueryClientProvider>
              {children}
              <Toaster />
            </QueryClientProvider>
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
